require 'rubygems'
require 'bundler'
Bundler.setup(:default, :ci)

require 'csv'
require 'json'
require 'time'
require 'io/wait'

require 'colorize'

require_relative './paths.rb'
require_relative './errors.rb'
require_relative './test.rb'
require_relative './html.rb'
require_relative './reference.rb'
require_relative './curator.rb'
require_relative './datatypes.rb'
require_relative './dictionary.rb'

require_relative './document/document.rb'
require_relative './document/element.rb'
require_relative './document/composite.rb'
require_relative './document/structure.rb'
require_relative './document/punctuation.rb'
require_relative './document/segment_rule.rb'
require_relative './document/date.rb'
require_relative './document/tag.rb'
require_relative './document/segment.rb'
require_relative './document/line.rb'

#require_relative './segments/una.rb'
#require_relative './segments/unh.rb'

require_relative './_segments/alc.rb'
require_relative './_segments/ali.rb'
require_relative './_segments/bgm.rb'
require_relative './_segments/cci.rb'
require_relative './_segments/cdi.rb'
require_relative './_segments/com.rb'
require_relative './_segments/cnt.rb'
require_relative './_segments/cps.rb'
require_relative './_segments/cta.rb'
require_relative './_segments/cux.rb'
require_relative './_segments/dtm.rb'
require_relative './_segments/efi.rb'
require_relative './_segments/eqd.rb'
require_relative './_segments/erc.rb'
require_relative './_segments/ftx.rb'
require_relative './_segments/gid.rb'
require_relative './_segments/gin.rb'
require_relative './_segments/gir.rb'
require_relative './_segments/imd.rb'
require_relative './_segments/inv.rb'
require_relative './_segments/lin.rb'
require_relative './_segments/loc.rb'
require_relative './_segments/mea.rb'
require_relative './_segments/moa.rb'
require_relative './_segments/nad.rb'
require_relative './_segments/pac.rb'
require_relative './_segments/pai.rb'
require_relative './_segments/pcd.rb'
require_relative './_segments/pci.rb'
require_relative './_segments/pia.rb'
require_relative './_segments/pri.rb'
require_relative './_segments/pyt.rb'
require_relative './_segments/qty.rb'
require_relative './_segments/rff.rb'
require_relative './_segments/sgp.rb'
require_relative './_segments/tax.rb'
require_relative './_segments/tdt.rb'

require_relative './_segments/una.rb'
require_relative './_segments/unb.rb'
require_relative './_segments/unh.rb'
require_relative './_segments/uns.rb'
require_relative './_segments/unt.rb'
require_relative './_segments/unz.rb'

require_relative './document/segment_map.rb'

require_relative './cli.rb'